---
title: "Relaciones multidimensionales"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  comment = "#>",
  out.width = "100%"
)
```

```{r setup}
library(labinstrumentos)

lab_instrumentos <- obtener_datos()[region == 1]

vars <- c("clean_problema", "clean_causa", "clean_consecuencia")

lab_instrumentos[j = (vars) := lapply(.SD, gsub, pattern = "macrozona-austral", replacement = ""), 
                 .SDcols = vars]
```

# Interrelación de términos, instrumentos y su clasificación

## Términos de una palabra

```{r}
crear_sankey(lab_instrumentos,
             n_words = 1,     # Número de palabras juntas
             freq_minima = 4, # Frecuencia mínima para la inclusión
             height = 850)    # Altura en píxeles del gráfico
```

## Términos de dos palabras

```{r}
crear_sankey(lab_instrumentos,
             n_words = 2, 
             freq_minima = 3,
             height = 850)
```

## Términos de tres palabras

```{r}
crear_sankey(lab_instrumentos,
             n_words = 3, 
             freq_minima = 2, 
             height = 850)
```
