#' Datos del Laboratorio de Instrumentos
#'
#' Datos, análisis y visualizaciones del laboratorio de intrumentos.
#'
#' @format Un data frame con 158 filas y 11 variables:
#'
#'   - \code{laboratorio}: ...
#'   - \code{grupo}: ...
#'   - \code{problema}: ...
#'   - \code{cluster_manual_problema}: ...
#'   - \code{clean_problema}: ...
#'   - \code{cluster_manual_causa}: ...
#'   - \code{causa}: ...
#'   - \code{clean_causa}: ...
#'   - \code{consecuencia}: ...
#'   - \code{clean_consecuencia}: ...
#'   - \code{region}: ...
#'
#' @source Los datos fueron recopilados del laboratorio de instrumentos.
"lab_instrumentos"
